//
//  ProdutBottomSheetPresenter.swift
//  TestExample
//
//  Created by Игорь Дикань on 20.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProdutBottomSheetPresentationLogic {
    func presentProduct(with data: CatalogViewModel.ProductModel)
}

final class ProdutBottomSheetPresenter {
    
    // MARK: - External vars
    weak var viewController: ProdutBottomSheetDisplayLogic?
}

// MARK: - Presentation logic
extension ProdutBottomSheetPresenter: ProdutBottomSheetPresentationLogic {
    
    func presentProduct(with data: CatalogViewModel.ProductModel) {
        viewController?.displayProduct(with: data)
    }
}
