//
//  ProdutBottomSheetInteractor.swift
//  TestExample
//
//  Created by Игорь Дикань on 20.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProdutBottomSheetBusinessLogic {
    func fetchProduct()
}

protocol ProdutBottomSheetDataStore: class {
    var product: CatalogViewModel.ProductModel? { get set }
}

final class ProdutBottomSheetInteractor {
    
    // MARK: - External vars
    var presenter: ProdutBottomSheetPresentationLogic?
    var worker: ProdutBottomSheetWorker?
    var product: CatalogViewModel.ProductModel?
    
    // MARK: - Internal vars
    
}

// MARK: - Business logic
extension ProdutBottomSheetInteractor: ProdutBottomSheetBusinessLogic {
    
    func fetchProduct() {
        guard let data = product else {
            return
        }
        presenter?.presentProduct(with: data)
    }
}

// MARK: - Data store
extension ProdutBottomSheetInteractor: ProdutBottomSheetDataStore {
    
}
