//
//  ProdutBottomSheetRouter.swift
//  TestExample
//
//  Created by Игорь Дикань on 20.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProdutBottomSheetRoutingLogic {
    func routeToBack()
}

protocol ProdutBottomSheetDataPassing {
    var dataStore: ProdutBottomSheetDataStore? { get }
}

final class ProdutBottomSheetRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: ProdutBottomSheetViewController?
    weak var dataStore: ProdutBottomSheetDataStore?
}

// MARK: - Routing logic
extension ProdutBottomSheetRouter: ProdutBottomSheetRoutingLogic {
    
    func routeToBack() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}

// MARK: - Data passing
extension ProdutBottomSheetRouter: ProdutBottomSheetDataPassing {
    
}
