//
//  CardRouter.swift
//  TestExample
//
//  Created by Игорь Дикань on 20.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CardRoutingLogic {
    
}

protocol CardDataPassing {
    var dataStore: CardDataStore? { get }
}

final class CardRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: CardViewController?
    weak var dataStore: CardDataStore?
}

// MARK: - Routing logic
extension CardRouter: CardRoutingLogic {
    
}

// MARK: - Data passing
extension CardRouter: CardDataPassing {
    
}
