//
//  MainInteractor.swift
//  TestExample
//
//  Created by Игорь Дикань on 19.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    
}

protocol MainDataStore: class {
    //var name: String { get set }
}

final class MainInteractor {
    
    // MARK: - External vars
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    //var name: String = ""
    
}

// MARK: - Business logic
extension MainInteractor: MainBusinessLogic {
    
}

// MARK: - Data store
extension MainInteractor: MainDataStore {
    
}
