//
//  CatalogInteractor.swift
//  TestExample
//
//  Created by Игорь Дикань on 19.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol CatalogBusinessLogic {
    func prepareCatalog()
    func updateCatalog()
}

protocol CatalogDataStore: class {
    var product: String { get set }
}

final class CatalogInteractor {
    
    // MARK: - External vars
    var presenter: CatalogPresentationLogic?
    var worker: CatalogWorker?
    var product: String = ""
    
    // MARK: - Internal vars
    private var categories: [String] = []
    private var products: [CatalogViewModel.ProductModel] = []
    private let realmInstance = RealmService.shared
}

// MARK: - Business logic
extension CatalogInteractor: CatalogBusinessLogic {
    
    func prepareCatalog() {
        let data = fetchData()
        self.categories = data.categories
        self.products = data.products
        writeToRealm(categories: categories, products: products)
        updateCatalog()
    }
    
    func updateCatalog() {
        let response = CatalogPresenterResponse(products: products, categories: categories)
        presenter?.presentCatalog(response: response)
    }
}

// MARK: - Data store
extension CatalogInteractor: CatalogDataStore {
    
}

// MARK: - Private methods
private extension CatalogInteractor {
    
    func writeToRealm(categories: [String], products: [CatalogViewModel.ProductModel]) {
        
        realmInstance.deleteAll()
        
        let categoriesList = List<String>()
        let _ = categories.map { (category) in
            categoriesList.append(category)
        }
        
        let produtcList = List<ProductRealmModel>()
        
        let productArray = products.map { (product) -> ProductRealmModel in
            
            let item = ProductRealmModel(productId: product.productId,
                                         title: product.title,
                                         descrip: product.description,
                                         price: product.price,
                                         imageUrl: product.imageUrl,
                                         quantity: product.quantity,
                                         weight: product.weight,
                                         categories: product.categories,
                                         categoriesId: product.categoriesId)
            return item
        }
        let _ = productArray.map { (product) in
            produtcList.append(product)
        }
        
        let realmModel = CatalogRealmModel(categories: categoriesList, products: produtcList)
        realmInstance.create(realmModel)
    }
    
    func fetchData() -> CatalogViewModel{
        let categories = ["Роллы", "Суши", "Сеты", "Вок", "Салаты", "Соусы", "Закуски", "Напитки"]
        let products = [
            CatalogViewModel.ProductModel(productId: "productId1",
                                      title: "Ролл 1",
                                      description: "description",
                                      price: "130 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "235 г",
                                      sizePrice: [CatalogViewModel.SizePrice(size: "5 шт", price: "130 ₽"), CatalogViewModel.SizePrice(size: "10 шт", price: "260 ₽")],
                                      categories: "Роллы",
                                      categoriesId: "categoriesId1"),
            CatalogViewModel.ProductModel(productId: "productId2",
                                      title: "Ролл 2",
                                      description: "description",
                                      price: "150 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "250 г",
                                      sizePrice: [CatalogViewModel.SizePrice(size: "5 шт", price: "150 ₽"), CatalogViewModel.SizePrice(size: "10 шт", price: "300 ₽")],
                                      categories: "Роллы",
                                      categoriesId: "categoriesId1"),
            CatalogViewModel.ProductModel(productId: "productId3",
                                      title: "Суши",
                                      description: "description",
                                      price: "80 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "150 г",
                                      sizePrice: nil,
                                      categories: "Суши",
                                      categoriesId: "categoriesId2"),
            CatalogViewModel.ProductModel(productId: "productId4",
                                      title: "Сеты",
                                      description: "description",
                                      price: "580 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "1150 г",
                                      sizePrice: nil,
                                      categories: "Сеты",
                                      categoriesId: "categoriesId3"),
            CatalogViewModel.ProductModel(productId: "productId5",
                                      title: "Вок",
                                      description: "description",
                                      price: "180 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "350 г",
                                      sizePrice: nil,
                                      categories: "Вок",
                                      categoriesId: "categoriesId4"),
            CatalogViewModel.ProductModel(productId: "productId6",
                                      title: "Салаты",
                                      description: "description",
                                      price: "110 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "250 г",
                                      sizePrice: nil,
                                      categories: "Салаты",
                                      categoriesId: "categoriesId6"),
            CatalogViewModel.ProductModel(productId: "productId7",
                                      title: "Соусы",
                                      description: "description",
                                      price: "30 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "50 г",
                                      sizePrice: nil,
                                      categories: "Соусы",
                                      categoriesId: "categoriesId7"),
            CatalogViewModel.ProductModel(productId: "productId8",
                                      title: "Закуски",
                                      description: "description",
                                      price: "90 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "100 г",
                                      sizePrice: nil,
                                      categories: "Закуски",
                                      categoriesId: "categoriesId9"),
            CatalogViewModel.ProductModel(productId: "productId9",
                                      title: "Напитки",
                                      description: "description",
                                      price: "100 ₽",
                                      imageUrl: "",
                                      quantity: 0,
                                      weight: "500 г",
                                      sizePrice: nil,
                                      categories: "Напитки",
                                      categoriesId: "categoriesId10"),
        ]

        var data = CatalogViewModel()
        data.categories.append(contentsOf: categories)
        data.products.append(contentsOf: products)
        
        return data
    }
}
