//
//  CatalogPresenter.swift
//  TestExample
//
//  Created by Игорь Дикань on 19.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogPresentationLogic {
    func presentCatalog(response: CatalogPresenterResponse)
    func updateCatalog(response: CatalogPresenterResponse)
}

final class CatalogPresenter {
    
    // MARK: - External vars
    weak var viewController: CatalogDisplayLogic?
}

// MARK: - Presentation logic
extension CatalogPresenter: CatalogPresentationLogic {
    
    func presentCatalog(response: CatalogPresenterResponse) {
        let viewModel = CatalogViewModel(categories: response.categories, products: response.products)
        viewController?.displayCatalog(viewModel)
    }
    
    func updateCatalog(response: CatalogPresenterResponse) {
        
    }
}
