//
//  TabBarRouter.swift
//  TestExample
//
//  Created by Игорь Дикань on 20.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TabBarRoutingLogic {
    
}

protocol TabBarDataPassing {
    var dataStore: TabBarDataStore? { get }
}

final class TabBarRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: TabBarViewController?
    weak var dataStore: TabBarDataStore?
}

// MARK: - Routing logic
extension TabBarRouter: TabBarRoutingLogic {
    
}

// MARK: - Data passing
extension TabBarRouter: TabBarDataPassing {
    
}
